<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>body_function(e,t,a,n,c,m,r)e.yme.ymfunctio_743dc6</name>
   <tag></tag>
   <elementGuidId>7ff2a2f1-8df8-474e-ae19-09f32bea7a14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>body.dark.k_page-login.proMode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dark k_page-login proMode</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>!function(e,t,a,n,c,m,r){e.ym=e.ym||function(){(e.ym.a=e.ym.a||[]).push(arguments)},e.ym.l=1*new Date,m=t.createElement(a),r=t.getElementsByTagName(a)[0],m.async=1,m.src=&quot;https://mc.yandex.ru/metrika/tag.js&quot;,r.parentNode.insertBefore(m,r)}(window,document,&quot;script&quot;),ym(83890042,&quot;init&quot;,{clickmap:!0,trackLinks:!0,accurateTrackBounce:!0,webvisor:!0})&lt;div>&lt;img src=&quot;https://mc.yandex.ru/watch/83890042&quot; style=&quot;position:absolute;left:-9999px&quot; alt=&quot;&quot;/>&lt;/div>You need to enable JavaScript to run this app.PiyasalarAl-SatProfilCüzdanAyarlarRaporlarGelişmişTemelGiriş YapKayıt olGiriş YapBeni HatırlaŞifreni mi unuttun?Giriş YapHesabınız yok mu? Buradan kayıt olŞirketHakkımızdaMobil UygulamaKomisyon ve ÜcretlerYasalKara Para Aklamayı Önleme PolitikasıMüşteri Tanımlama PolitikasıŞartlar ve KoşullarTicari Elektronik İletiKişisel Verilerin Korunması KanunuDestekİletişimBu internet sitesinde sizlere daha iyi hizmet sunulabilmesi için çerezler kullanılmaktadır. Çerezler hakkında detaylı bilgi almak için Çerez Politikası metnini inceleyebilirsiniz.KapatPiyasaAl-SatCüzdanProfilCanlı Destekwindow.__lc=window.__lc||{},window.__lc.license=10016235,function(n,t,c){function i(n){return e._h?e._h.apply(null,n):e._q.push(n)}var e={_q:[],_h:null,_v:&quot;2.0&quot;,on:function(){i([&quot;on&quot;,c.call(arguments)])},once:function(){i([&quot;once&quot;,c.call(arguments)])},off:function(){i([&quot;off&quot;,c.call(arguments)])},get:function(){if(!e._h)throw new Error(&quot;[LiveChatWidget] You can't use getters before load.&quot;);return i([&quot;get&quot;,c.call(arguments)])},call:function(){i([&quot;call&quot;,c.call(arguments)])},init:function(){var n=t.createElement(&quot;script&quot;);n.async=!0,n.type=&quot;text/javascript&quot;,n.src=&quot;https://cdn.livechatinc.com/tracking.js&quot;,t.head.appendChild(n)}};!n.__lc.asyncInit&amp;&amp;e.init(),n.LiveChatWidget=n.LiveChatWidget||e}(window,document,[].slice)&lt;a href=&quot;https://www.livechatinc.com/chat-with/10016235/&quot; rel=&quot;nofollow&quot;>Chat with us&lt;/a>!function(e){function r(r){for(var n,i,l=r[0],a=r[1],f=r[2],c=0,s=[];c&lt;l.length;c++)i=l[c],Object.prototype.hasOwnProperty.call(o,i)&amp;&amp;o[i]&amp;&amp;s.push(o[i][0]),o[i]=0;for(n in a)Object.prototype.hasOwnProperty.call(a,n)&amp;&amp;(e[n]=a[n]);for(p&amp;&amp;p(r);s.length;)s.shift()();return u.push.apply(u,f||[]),t()}function t(){for(var e,r=0;r&lt;u.length;r++){for(var t=u[r],n=!0,l=1;l&lt;t.length;l++){var a=t[l];0!==o[a]&amp;&amp;(n=!1)}n&amp;&amp;(u.splice(r--,1),e=i(i.s=t[0]))}return e}var n={},o={1:0},u=[];function i(r){if(n[r])return n[r].exports;var t=n[r]={i:r,l:!1,exports:{}};return e[r].call(t.exports,t,t.exports,i),t.l=!0,t.exports}i.m=e,i.c=n,i.d=function(e,r,t){i.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:t})},i.r=function(e){&quot;undefined&quot;!=typeof Symbol&amp;&amp;Symbol.toStringTag&amp;&amp;Object.defineProperty(e,Symbol.toStringTag,{value:&quot;Module&quot;}),Object.defineProperty(e,&quot;__esModule&quot;,{value:!0})},i.t=function(e,r){if(1&amp;r&amp;&amp;(e=i(e)),8&amp;r)return e;if(4&amp;r&amp;&amp;&quot;object&quot;==typeof e&amp;&amp;e&amp;&amp;e.__esModule)return e;var t=Object.create(null);if(i.r(t),Object.defineProperty(t,&quot;default&quot;,{enumerable:!0,value:e}),2&amp;r&amp;&amp;&quot;string&quot;!=typeof e)for(var n in e)i.d(t,n,function(r){return e[r]}.bind(null,n));return t},i.n=function(e){var r=e&amp;&amp;e.__esModule?function(){return e.default}:function(){return e};return i.d(r,&quot;a&quot;,r),r},i.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},i.p=&quot;/&quot;;var l=this.webpackJsonpkointra=this.webpackJsonpkointra||[],a=l.push.bind(l);l.push=r,l=l.slice();for(var f=0;f&lt;l.length;f++)r(l[f]);var p=a;t()}([])id(&quot;loading-ui&quot;)/div[@class=&quot;loading-ui-overlay dark topbar&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;dark k_page-login proMode&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
   </webElementXpaths>
</WebElementEntity>
