<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_concat(Seilmemi resim kalmadnda Dorula, , y tklayn)_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>faebe9aa-cf62-46de-8c34-c0b5ce948841</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq24AzlJAR1bhHV_ucVqNtzl7iqdWTTzZEIgdnHrQp7pKmnbd45d7yqArRON-lPk2u94jBcUuquotWE9u32mubnvLVF_pzRhSfIAbx2yxOXHsZDyN_Q7zI8rT0J6bcqv-6EKn_3TZMvpM9LHe7AuFAZxCoYQ8_iro7lA0bb3Cpssun1oKR2Or3DWwKsWIsQY1THQE15yT96Q3S3jo96USnodG8mcqFA&amp;k=6Lfz9l0UAAAAAEvSAvegMiVuSsC6CfqKAzj1xGpe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/login/Page_Kointra/iframe_concat(html1bodyclass, , dark k_page_d4b2bd</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq24AzlJAR1bhHV_ucVqNtzl7iqdWTTzZEIgdnHrQp7pKmnbd45d7yqArRON-lPk2u94jBcUuquotWE9u32mubnvLVF_pzRhSfIAbx2yxOXHsZDyN_Q7zI8rT0J6bcqv-6EKn_3TZMvpM9LHe7AuFAZxCoYQ8_iro7lA0bb3Cpssun1oKR2Or3DWwKsWIsQY1THQE15yT96Q3S3jo96USnodG8mcqFA&amp;k=6Lfz9l0UAAAAAEvSAvegMiVuSsC6CfqKAzj1xGpe')])[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
