<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_concat(Seilmemi resim kalmadnda Dorula,_f6714a</name>
   <tag></tag>
   <elementGuidId>e069c34e-5b22-4dd1-a4b2-4142910249f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq255P-gLw71azlT5SeI0vIuEHbBACq_YRpRMOz3D8QzaP6xCgRXQahwKlvlQUQdGquHVSNe2BWM2Lj9VjX0bc_D39oEQljpI0Jux4VGy3znjuS8v4dfE-hgu_k85QmYbhcRHmJm272JnMf6mD7gIWUF5d4hFykWNeux8FLv_4EV2G88wWAoPGgMK8IaLGuR8ds5MnuwitWj5wyGkI8a_YjDdnnb7OA&amp;k=6Lfz9l0UAAAAAEvSAvegMiVuSsC6CfqKAzj1xGpe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/login/Page_Kointra/iframe_concat(html1bodyclass, , dark k_page_d4b2bd</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq255P-gLw71azlT5SeI0vIuEHbBACq_YRpRMOz3D8QzaP6xCgRXQahwKlvlQUQdGquHVSNe2BWM2Lj9VjX0bc_D39oEQljpI0Jux4VGy3znjuS8v4dfE-hgu_k85QmYbhcRHmJm272JnMf6mD7gIWUF5d4hFykWNeux8FLv_4EV2G88wWAoPGgMK8IaLGuR8ds5MnuwitWj5wyGkI8a_YjDdnnb7OA&amp;k=6Lfz9l0UAAAAAEvSAvegMiVuSsC6CfqKAzj1xGpe')])[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
