<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Yoksa, Atla dmesini tklayn_rc-image-tile-44_1_2_3</name>
   <tag></tag>
   <elementGuidId>ffcbb0ac-a0bf-4219-80fb-b160969f0acd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq27ixOLyJq8E9QTdCrJbf6vNJjlpl0-R_Co7PurfETCuQU8C1X-xVd0D48cHuaXLfrq3JBAshmebcMvFRKrfQXLrHDTFvJn7GA0ovy0qYg-pbRUivtCb6gJfIy1bUVPMAFKVxyXWPN-fDKWaKMZEdgeblNFJWVoNJDPw_OsRRHV3oguv-Ttb8DtCbf4hwx4_dPS7GpEfxk3obard1CL9CkiQxxvFOg&amp;k=6Lfz9l0UAAAAAEvSAvegMiVuSsC6CfqKAzj1xGpe&amp;id=6a1973e8dfbf8ae6</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/login/Page_Kointra/iframe_concat(html1bodyclass, , dark k_page_d4b2bd</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq27ixOLyJq8E9QTdCrJbf6vNJjlpl0-R_Co7PurfETCuQU8C1X-xVd0D48cHuaXLfrq3JBAshmebcMvFRKrfQXLrHDTFvJn7GA0ovy0qYg-pbRUivtCb6gJfIy1bUVPMAFKVxyXWPN-fDKWaKMZEdgeblNFJWVoNJDPw_OsRRHV3oguv-Ttb8DtCbf4hwx4_dPS7GpEfxk3obard1CL9CkiQxxvFOg&amp;k=6Lfz9l0UAAAAAEvSAvegMiVuSsC6CfqKAzj1xGpe&amp;id=6a1973e8dfbf8ae6')])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
