<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Kpr_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>23efb7d4-5994-4f51-8875-3876c21b0f2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq246rU-1rp6B5ZmnB1YB6CuzFflLHfJAIpnhf4oYD8TdU2h2BxXxRosRaqDSg7d-8eXrFnMJdev_VcqO4Kykmq-0ykiCOYzltYGbSrKHSsu9tvUHin5HzDIJFp5mjyLTWxXYX8xQDpDWZM_i6lXqHeqHHRjCS1xk6fdwsQUxbuKQm8qrT5YV8s-Fcq5yUgwBA1bMtmdWF9LPBKwkc962RZ_8tjaPpw&amp;k=6Lfz9l0UAAAAAEvSAvegMiVuSsC6CfqKAzj1xGpe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/login/Page_Kointra/iframe_concat(html1bodyclass, , dark k_page_d4b2bd</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq246rU-1rp6B5ZmnB1YB6CuzFflLHfJAIpnhf4oYD8TdU2h2BxXxRosRaqDSg7d-8eXrFnMJdev_VcqO4Kykmq-0ykiCOYzltYGbSrKHSsu9tvUHin5HzDIJFp5mjyLTWxXYX8xQDpDWZM_i6lXqHeqHHRjCS1xk6fdwsQUxbuKQm8qrT5YV8s-Fcq5yUgwBA1bMtmdWF9LPBKwkc962RZ_8tjaPpw&amp;k=6Lfz9l0UAAAAAEvSAvegMiVuSsC6CfqKAzj1xGpe')])[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
