<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Yoksa, Atla dmesini tklayn_rc-image-tile-44_1_2</name>
   <tag></tag>
   <elementGuidId>1f98e5ef-2eba-4215-b224-6b929a5e50fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq27xyD206YmgoEzO6VglfpW2g5wgJgLxLM4vugLmcTmFV761J_B2w-n0NB2Y51TSumPcybax_z5kxn49lQmPLi8u3zO-BsnbxUBpcNW6W5cqDdIc-w86aDX-vxP16WkeTyeOAUcij7v5i254GwbkKDU4BSHJdunBf-LNXVIq8ISkSV9VnTNG6r78DkLwTJthWzm35YQ-askstiyDnHRvvjcr5Oq_qg&amp;k=6Lfz9l0UAAAAAEvSAvegMiVuSsC6CfqKAzj1xGpe&amp;id=d00369dd5ab5cd88</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/login/Page_Kointra/iframe_concat(html1bodyclass, , dark k_page_d4b2bd</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq27xyD206YmgoEzO6VglfpW2g5wgJgLxLM4vugLmcTmFV761J_B2w-n0NB2Y51TSumPcybax_z5kxn49lQmPLi8u3zO-BsnbxUBpcNW6W5cqDdIc-w86aDX-vxP16WkeTyeOAUcij7v5i254GwbkKDU4BSHJdunBf-LNXVIq8ISkSV9VnTNG6r78DkLwTJthWzm35YQ-askstiyDnHRvvjcr5Oq_qg&amp;k=6Lfz9l0UAAAAAEvSAvegMiVuSsC6CfqKAzj1xGpe&amp;id=d00369dd5ab5cd88')])[11]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
